export const ACCOUNT_ABI = {
  address: "0x1",
  name: "account",
  friends: [
    "0x1::aptos_account",
    "0x1::coin",
    "0x1::genesis",
    "0x1::multisig_account",
    "0x1::resource_account",
    "0x1::transaction_validation",
  ],
  exposed_functions: [
    {
      name: "create_account",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address"],
      return: ["signer"],
    },
    {
      name: "create_authorized_signer",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: ["signer"],
    },
    {
      name: "create_framework_reserved_account",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address"],
      return: ["signer", "0x1::account::SignerCapability"],
    },
    {
      name: "create_guid",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: ["0x1::guid::GUID"],
    },
    {
      name: "create_resource_account",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: ["signer", "0x1::account::SignerCapability"],
    },
    {
      name: "create_resource_address",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&address", "vector<u8>"],
      return: ["address"],
    },
    {
      name: "create_signer_with_capability",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&0x1::account::SignerCapability"],
      return: ["signer"],
    },
    {
      name: "exists_at",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "get_authentication_key",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["vector<u8>"],
    },
    {
      name: "get_guid_next_creation_num",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_rotation_capability_offer_for",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["address"],
    },
    {
      name: "get_sequence_number",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_signer_capability_address",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&0x1::account::SignerCapability"],
      return: ["address"],
    },
    {
      name: "get_signer_capability_offer_for",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["address"],
    },
    {
      name: "increment_sequence_number",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["address"],
      return: [],
    },
    {
      name: "initialize",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "is_rotation_capability_offered",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "is_signer_capability_offered",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "new_event_handle",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: ["drop", "store"],
        },
      ],
      params: ["&signer"],
      return: ["0x1::event::EventHandle<T0>"],
    },
    {
      name: "offer_rotation_capability",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>", "u8", "vector<u8>", "address"],
      return: [],
    },
    {
      name: "offer_signer_capability",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>", "u8", "vector<u8>", "address"],
      return: [],
    },
    {
      name: "register_coin",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      params: ["address"],
      return: [],
    },
    {
      name: "revoke_any_rotation_capability",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "revoke_any_signer_capability",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "revoke_rotation_capability",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "revoke_signer_capability",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "rotate_authentication_key",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "u8",
        "vector<u8>",
        "u8",
        "vector<u8>",
        "vector<u8>",
        "vector<u8>",
      ],
      return: [],
    },
    {
      name: "rotate_authentication_key_internal",
      visibility: "friend",
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "vector<u8>"],
      return: [],
    },
    {
      name: "rotate_authentication_key_with_rotation_capability",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address", "u8", "vector<u8>", "vector<u8>"],
      return: [],
    },
    {
      name: "verify_signed_message",
      visibility: "public",
      is_entry: false,
      is_view: false,
      generic_type_params: [
        {
          constraints: ["drop"],
        },
      ],
      params: ["address", "u8", "vector<u8>", "vector<u8>", "T0"],
      return: [],
    },
  ],
  structs: [
    {
      name: "Account",
      is_native: false,
      abilities: ["store", "key"],
      generic_type_params: [],
      fields: [
        {
          name: "authentication_key",
          type: "vector<u8>",
        },
        {
          name: "sequence_number",
          type: "u64",
        },
        {
          name: "guid_creation_num",
          type: "u64",
        },
        {
          name: "coin_register_events",
          type: "0x1::event::EventHandle<0x1::account::CoinRegisterEvent>",
        },
        {
          name: "key_rotation_events",
          type: "0x1::event::EventHandle<0x1::account::KeyRotationEvent>",
        },
        {
          name: "rotation_capability_offer",
          type: "0x1::account::CapabilityOffer<0x1::account::RotationCapability>",
        },
        {
          name: "signer_capability_offer",
          type: "0x1::account::CapabilityOffer<0x1::account::SignerCapability>",
        },
      ],
    },
    {
      name: "CapabilityOffer",
      is_native: false,
      abilities: ["store"],
      generic_type_params: [
        {
          constraints: [],
        },
      ],
      fields: [
        {
          name: "for",
          type: "0x1::option::Option<address>",
        },
      ],
    },
    {
      name: "CoinRegisterEvent",
      is_native: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "type_info",
          type: "0x1::type_info::TypeInfo",
        },
      ],
    },
    {
      name: "KeyRotationEvent",
      is_native: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "old_authentication_key",
          type: "vector<u8>",
        },
        {
          name: "new_authentication_key",
          type: "vector<u8>",
        },
      ],
    },
    {
      name: "OriginatingAddress",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "address_map",
          type: "0x1::table::Table<address, address>",
        },
      ],
    },
    {
      name: "RotationCapability",
      is_native: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "account",
          type: "address",
        },
      ],
    },
    {
      name: "RotationCapabilityOfferProofChallenge",
      is_native: false,
      abilities: ["drop"],
      generic_type_params: [],
      fields: [
        {
          name: "sequence_number",
          type: "u64",
        },
        {
          name: "recipient_address",
          type: "address",
        },
      ],
    },
    {
      name: "RotationCapabilityOfferProofChallengeV2",
      is_native: false,
      abilities: ["drop"],
      generic_type_params: [],
      fields: [
        {
          name: "chain_id",
          type: "u8",
        },
        {
          name: "sequence_number",
          type: "u64",
        },
        {
          name: "source_address",
          type: "address",
        },
        {
          name: "recipient_address",
          type: "address",
        },
      ],
    },
    {
      name: "RotationProofChallenge",
      is_native: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        {
          name: "sequence_number",
          type: "u64",
        },
        {
          name: "originator",
          type: "address",
        },
        {
          name: "current_auth_key",
          type: "address",
        },
        {
          name: "new_public_key",
          type: "vector<u8>",
        },
      ],
    },
    {
      name: "SignerCapability",
      is_native: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "account",
          type: "address",
        },
      ],
    },
    {
      name: "SignerCapabilityOfferProofChallenge",
      is_native: false,
      abilities: ["drop"],
      generic_type_params: [],
      fields: [
        {
          name: "sequence_number",
          type: "u64",
        },
        {
          name: "recipient_address",
          type: "address",
        },
      ],
    },
    {
      name: "SignerCapabilityOfferProofChallengeV2",
      is_native: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        {
          name: "sequence_number",
          type: "u64",
        },
        {
          name: "source_address",
          type: "address",
        },
        {
          name: "recipient_address",
          type: "address",
        },
      ],
    },
  ],
} as const;
